### ISSUE TITLE
Download feature does nothing

### ISSUE THREAD

**Issue by survive9** [skyguy126/Xposed-SoundCloudDownloader#16] opened 2018-03-09 06:40 UTC
Running Magisk 16 + Systemless Xposed on G920T with Lineage OS 14.1 latest nightly as of this writing. The download button shows up in the 02.26.18 version of soundcloud, but when clicking it no prompt shows up in the status bar that the song is being downloaded. Sure enough, nothing is downloaded to the music folder. Tried reinstalling both the xposed module and the app.

**Comment by skyguy126** [comment] 2018-03-09 08:53
Can you post the Xposed log here after the track gets downloaded.

**Comment by survive9** [comment] 2018-03-09 14:56
[xposed_error_20180309_095459.log](https://github.com/skyguy126/Xposed-SoundCloudDownloader/files/1797305/xposed_error_20180309_095459.log)

This is what I get after attempting to download

**Comment by skyguy126** [comment] 2018-03-09 17:58
thanks, I think I know what the issue is. Can you download other tracks without issue or does this happen for every track?

**Comment by survive9** [comment] 2018-03-09 18:03
After testing by trying to download random songs, it seems to work for most of the songs on soundcloud except for the ones I actually want to download lol.

**Comment by survive9** [comment] 2018-03-09 18:08
After trying to download more I have ran into a few more songs that didn't download. It seems most of them download but a few do not. Maybe different audio format that isn't recognized by the downloader?

**Comment by skyguy126** [comment] 2018-03-09 18:17
its because the songs you are trying to download are probably missing a genre/album art and the module is trying to find them when they don't exist. will fix in a new update soon.

**Comment by FahadYousafMahar** [comment] 2018-03-09 18:17
Thanks @skyguy126

**Comment by survive9** [comment] 2018-03-09 18:22
That's strange, the album art is on soundcloud. Must be the genre then, thanks.

**Comment by skyguy126** [comment] 2018-03-09 18:29
Can you try and see if this debug version works? [REDACTED]

EDIT: just realized I need to change one more thing

**Comment by FahadYousafMahar** [comment] 2018-03-09 18:32
Error while installing debug package

**Comment by survive9** [comment] 2018-03-09 18:35
I know you deleted the link but the debug app still worked when used on a track that did didn't download before

**Comment by skyguy126** [comment] 2018-03-09 18:38
ok this one _should_ work: https://www.dropbox.com/s/5dqhx9r3q0fhti2/scd-v1.5.3_debug.apk?dl=0

Let me know if it spits out any errors in the Xposed log, thanks

EDIT: you might need to reinstall the module if you tried the removed link above already since the version code is the same

**Comment by survive9** [comment] 2018-03-09 18:46
New debug version also works, no errors in xposed log

**Comment by FahadYousafMahar** [comment] 2018-03-09 18:46
YAHOO !!!
It Works. It downloaded the tracks which were previously unTouchable.

**Comment by skyguy126** [comment] 2018-03-09 18:51
Fixed with 57c9213ba10c094bd645ba37e4d5dbd780f3921f.

**Closed as completed by skyguy126** 2018-03-09 18:51 UTC
Labels: bug
